# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^

print(np.linspace(0.0, 1.0, 15))

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:
# write your code here ^_^

array1 = np.array([1.1, 2.1, 3.1])
array2 = np.array([4.1, 5.1, 6.1])
array3 = np.array([7.1, 8.1, 9.1])
array4 = np.array([10.1, 11.1, 12.1])

data_3d = np.stack((array1, array2, array3, array4), axis=0)

print(data_3d)


[[ 1.4  2.6  3.3]
 [ 4.1  5.8  6.4]
 [ 7.1  8.4  9.1]
 [10.1 11.2 12.3]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [5]:
# write your code here ^_^

print(f"Array type: {type(data_3d)}")
print(f"Elements datatype: {data_3d.dtype}")
print(f"Array shape: {data_3d.shape}")
print(f"Array size: {data_3d.size}")
print(f"Array dimension: {data_3d.ndim}")


Array type: <class 'numpy.ndarray'>
Elements datatype: float64
Array shape: (4, 3)
Array size: 12
Array dimension: 2


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [7]:
# write your code here ^_^
data_4d_1 = np.expand_dims(data_3d, axis=0) 

print(f"New array dimension (Approach 1): {data_4d_1.ndim}")
print(f"New array shape (Approach 1): {data_4d_1.shape}")


New array dimension (Approach 1): 3
New array shape (Approach 1): (1, 4, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [9]:
# write your code here ^_^


data_int = data_3d.astype(int) 

print("New array (integer elements):")
print(data_int)


New array (integer elements):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [11]:
# write your code here ^_^


print("Elements using nditer:")
for element in np.nditer(data_int):
  print(element)


Elements using nditer:
1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [13]:
# write your code here ^_^

element_exists = 8 in data_int

if element_exists:
  print("Number 8 exists in the array (but specific location not retrieved with slicing)")
else:
  print("Number 8 not found in the array")


Number 8 exists in the array (but specific location not retrieved with slicing)


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [15]:
# write your code here ^_^

number_5 = data_int[1],[1]  
number_6 = data_int[1],[2] 

print("Number 5:", number_5)
print("Number 6:", number_6)


Number 5: (array([4, 5, 6]), [1])
Number 6: (array([4, 5, 6]), [2])


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [18]:
# write your code here ^_^

indices = np.where(data_int == 8)

if indices[0].size > 0:

  print("Number 8 found at indices:", indices)
else:
  print("Number 8 not found in the array")


Number 8 found at indices: (array([2], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [29]:
# write your code here ^_^

data_reshaped = data_int.reshape(3, 2, 2)

print("Reshaped array:")
print(data_reshaped)


Reshaped array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [30]:
# write your code here ^_^

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2))

print(joined_array)


[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [31]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2), axis=1)

print(joined_array)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [32]:
# write your code here ^_^

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2), axis=1)

split_arr1 = joined_array[:, :2]  # First two columns
split_arr2 = joined_array[:, 2:]  # Last two columns

print("Split array 1:", split_arr1)
print("Split array 2:", split_arr2)

Split array 1: [['A' 'B']
 ['E' 'F']]
Split array 2: [['C' 'D']
 ['G' 'H']]
