In [ ]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [32]:
# write your code here ^_^

x = np.ones(array_size)
print (x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [31]:
# write your code here ^_^

y = np.zeros(array_size)
print (y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [30]:
# write your code here ^_^

x = np.ones(array_size)

y = np.zeros(array_size)
result = x + y
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [29]:
# write your code here ^_^


x = np.ones(array_size)
print("Dimension of x array:", x.ndim)
print("Shape of x array:", x.shape)
print("Size of x array:", x.size)
print("Data type of x array:", x.dtype)


Dimension of x array: 1
Shape of x array: (10,)
Size of x array: 10
Data type of x array: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [23]:
# write your code here ^_^


w = np.array([[11, 12], [13, 14], [15, 16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [13]:
# write your code here ^_^


z = np.array([1, 2, 3])
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [12]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

print(newArray)



[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [11]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

for row in newArray:
    for element in row:
        print(element, end=' ')
    print()


1 11 12 
2 13 14 
3 15 16 


## Q#9: Reverse the columns and rows of "newArray".

In [10]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

reversedArray = np.flip(newArray, axis=0)
reversedArray = np.flip(reversedArray, axis=1)

print(reversedArray)


[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [9]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

newArray -= 1

print(newArray)


[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [8]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

smallest = np.min(newArray)
largest = np.max(newArray)

print("Smallest :", smallest)
print("Largest :", largest)


Smallest : 1
Largest : 16


## Q#12: Print the first row of "newArray" using indexing.

In [7]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

first_row = newArray[0]

print("First row of newArray:", first_row)


First row of newArray: [ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [6]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

number_12_index = np.where(newArray == 12)
number_12 = newArray[number_12_index]

print("Number equals 12:", number_12[0])


Number equals 12: 12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [5]:
# write your code here ^_^
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

indices_0 = np.where(newArray == 0)
indices_13 = np.where(newArray == 13)

numbers_0 = newArray[indices_0]
numbers_13 = newArray[indices_13]

print("Numbers equal to 0:", numbers_0)
print("Numbers equal to 13:", numbers_13)


Numbers equal to 0: []
Numbers equal to 13: [13]


## Q#15: Change the shape of "newArray" to (9,1).

In [3]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

newArray_reshaped = newArray.reshape((9, 1))

print(newArray_reshaped)


[[ 1]
 [11]
 [12]
 [ 2]
 [13]
 [14]
 [ 3]
 [15]
 [16]]


## Q#16: Change the shape of "newArray" to (3,3).

In [4]:
# write your code here ^_^


z = np.array([1, 2, 3])
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

newArray = np.hstack((z[:, np.newaxis], w))

newArray_reshaped = newArray.reshape((3, 3))

print(newArray_reshaped)


[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


# Well Done 🎉